twig:
    file_name_pattern: '*.twig'
    globals:
        idioma:
            name: Idioma International
            url: '%env(APP_URL)%'
            address: Avenue Chute de Lofoy 16, Kintambo
            city: Kinshasa, RDC
            find_teacher: '%env(APP_URL)%/teachers'
            teacher_dashboard: '%env(APP_URL)%/dashboard'
            dashboard: '%env(APP_URL)%/dashboard'


when@test:
    twig:
        strict_variables: true
