<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250902152814 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attachment (id INT AUTO_INCREMENT NOT NULL, course_id INT DEFAULT NULL, user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, size INT UNSIGNED NOT NULL, mime_type VARCHAR(255) DEFAULT NULL, original_name VARCHAR(255) DEFAULT NULL, dimensions JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_795FD9BB591CC992 (course_id), INDEX IDX_795FD9BBA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE certification (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE certification_language (certification_id INT NOT NULL, language_id INT NOT NULL, INDEX IDX_1B340722CB47068A (certification_id), INDEX IDX_1B34072282F1BAF4 (language_id), PRIMARY KEY(certification_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact (id INT AUTO_INCREMENT NOT NULL, lastname VARCHAR(255) NOT NULL, email VARCHAR(180) NOT NULL, content LONGTEXT NOT NULL, phone VARCHAR(15) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE course (id INT AUTO_INCREMENT NOT NULL, language_id INT NOT NULL, teacher_id INT DEFAULT NULL, currency_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, status VARCHAR(255) NOT NULL, difficulty VARCHAR(3) NOT NULL, level VARCHAR(3) NOT NULL, duration INT NOT NULL, state VARCHAR(255) DEFAULT NULL, is_paid TINYINT(1) NOT NULL, amount DOUBLE PRECISION DEFAULT \'0\' NOT NULL, amount_promo DOUBLE PRECISION DEFAULT \'0\' NOT NULL, is_promote TINYINT(1) DEFAULT 0 NOT NULL, short_description VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_169E6FB982F1BAF4 (language_id), INDEX IDX_169E6FB941807E1D (teacher_id), INDEX IDX_169E6FB938248176 (currency_id), INDEX IDX_169E6FB9C76F1F52 (deleted_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE course_category (course_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_AFF87497591CC992 (course_id), INDEX IDX_AFF8749712469DE2 (category_id), PRIMARY KEY(course_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE currency (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, min VARCHAR(3) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE disponibility (id INT AUTO_INCREMENT NOT NULL, teacher_id INT DEFAULT NULL, day VARCHAR(255) NOT NULL, start VARCHAR(255) NOT NULL, end VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL, INDEX IDX_38BB926041807E1D (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE faq (id INT AUTO_INCREMENT NOT NULL, question VARCHAR(255) NOT NULL, answer VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fee (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(1) NOT NULL, value DOUBLE PRECISION NOT NULL, min DOUBLE PRECISION DEFAULT NULL, max DOUBLE PRECISION DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbox_message (id INT AUTO_INCREMENT NOT NULL, author_id INT DEFAULT NULL, attachment_id INT DEFAULT NULL, tag_message_id INT DEFAULT NULL, thread_id INT NOT NULL, deleted_by_id INT DEFAULT NULL, body LONGTEXT NOT NULL, received_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', read_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_83893680F675F31B (author_id), UNIQUE INDEX UNIQ_83893680464E68B (attachment_id), INDEX IDX_83893680F6619178 (tag_message_id), INDEX IDX_83893680E2904019 (thread_id), INDEX IDX_83893680C76F1F52 (deleted_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbox_thread (id INT AUTO_INCREMENT NOT NULL, teacher_id INT DEFAULT NULL, course_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deleted_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_B08E49AB41807E1D (teacher_id), UNIQUE INDEX UNIQ_B08E49AB591CC992 (course_id), INDEX IDX_B08E49ABC76F1F52 (deleted_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE inbox_thread_user (inbox_thread_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_3E33875098D72D6A (inbox_thread_id), INDEX IDX_3E338750A76ED395 (user_id), PRIMARY KEY(inbox_thread_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE language (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, flag VARCHAR(2) DEFAULT NULL, locale VARCHAR(10) DEFAULT NULL, is_active TINYINT(1) NOT NULL, is_public TINYINT(1) DEFAULT 0 NOT NULL, teachers INT DEFAULT 0 NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE login_attempt (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_8C11C1BA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE newsletter (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, subject VARCHAR(255) NOT NULL, content VARCHAR(255) NOT NULL, read_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_BF5476CAA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `order` (id INT AUTO_INCREMENT NOT NULL, currency_id INT DEFAULT NULL, user_id INT DEFAULT NULL, transaction_id INT DEFAULT NULL, reference VARCHAR(255) NOT NULL, amount DOUBLE PRECISION NOT NULL, status VARCHAR(255) NOT NULL, operator VARCHAR(10) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_F529939838248176 (currency_id), INDEX IDX_F5299398A76ED395 (user_id), UNIQUE INDEX UNIQ_F52993982FC0CB0F (transaction_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order_product (id INT AUTO_INCREMENT NOT NULL, teacher_id INT NOT NULL, package_id INT NOT NULL, command_id INT NOT NULL, amount DOUBLE PRECISION DEFAULT NULL, INDEX IDX_2530ADE641807E1D (teacher_id), INDEX IDX_2530ADE6F44CABFF (package_id), INDEX IDX_2530ADE633E1689A (command_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE otp (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, pass VARCHAR(255) NOT NULL, expired_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', type VARCHAR(255) NOT NULL, phone VARCHAR(15) NOT NULL, type_id INT NOT NULL, INDEX IDX_A79C98C1A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE package (id INT AUTO_INCREMENT NOT NULL, activated_by_id INT DEFAULT NULL, hours INT NOT NULL, discount DOUBLE PRECISION NOT NULL, is_active TINYINT(1) NOT NULL, activated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deactivated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_DE686795E00EB9A0 (activated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment (id INT AUTO_INCREMENT NOT NULL, currency_id INT NOT NULL, user_id INT NOT NULL, executed_by_id INT DEFAULT NULL, reference VARCHAR(255) NOT NULL, amount DOUBLE PRECISION NOT NULL, method VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', paid_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', method_data VARCHAR(255) DEFAULT NULL, INDEX IDX_6D28840D38248176 (currency_id), INDEX IDX_6D28840DA76ED395 (user_id), INDEX IDX_6D28840D8B35AB5C (executed_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE planning (id INT AUTO_INCREMENT NOT NULL, teacher_id INT DEFAULT NULL, course_id INT DEFAULT NULL, start DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', end DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', meeting_link VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_D499BFF641807E1D (teacher_id), INDEX IDX_D499BFF6591CC992 (course_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE planning_user (planning_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_4545DE073D865311 (planning_id), INDEX IDX_4545DE07A76ED395 (user_id), PRIMARY KEY(planning_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pricing (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, amount DOUBLE PRECISION DEFAULT NULL, period INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rate (id INT AUTO_INCREMENT NOT NULL, currency_id INT NOT NULL, reference VARCHAR(255) NOT NULL, value DOUBLE PRECISION NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_DFEC3F3938248176 (currency_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rating (id INT AUTO_INCREMENT NOT NULL, teacher_id INT DEFAULT NULL, course_id INT DEFAULT NULL, user_id INT NOT NULL, stars DOUBLE PRECISION NOT NULL, comment VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_D889262241807E1D (teacher_id), INDEX IDX_D8892622591CC992 (course_id), INDEX IDX_D8892622A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE refresh_tokens (id INT AUTO_INCREMENT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid DATETIME NOT NULL, UNIQUE INDEX UNIQ_9BACE7E1C74F2195 (refresh_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reviews (id INT AUTO_INCREMENT NOT NULL, course_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, comment LONGTEXT NOT NULL, INDEX IDX_6970EB0F591CC992 (course_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE social (id INT AUTO_INCREMENT NOT NULL, teacher_id INT DEFAULT NULL, type VARCHAR(20) NOT NULL, link VARCHAR(255) NOT NULL, icon VARCHAR(50) DEFAULT NULL, INDEX IDX_7161E18741807E1D (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE spoken_language (id INT AUTO_INCREMENT NOT NULL, teacher_id INT NOT NULL, level VARCHAR(15) NOT NULL, language VARCHAR(255) NOT NULL, INDEX IDX_A861E9D841807E1D (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE subscriber (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, currency_id INT DEFAULT NULL, language_id INT DEFAULT NULL, activated_by_id INT DEFAULT NULL, verified_by_id INT DEFAULT NULL, description LONGTEXT NOT NULL, price DOUBLE PRECISION DEFAULT NULL, short_description VARCHAR(255) NOT NULL, experience VARCHAR(255) DEFAULT NULL, motivation VARCHAR(255) DEFAULT NULL, link VARCHAR(255) DEFAULT NULL, video VARCHAR(255) DEFAULT NULL, timezone VARCHAR(255) DEFAULT NULL, submited_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', step INT NOT NULL, profile VARCHAR(255) DEFAULT NULL, status VARCHAR(255) DEFAULT \'0\' NOT NULL, is_active TINYINT(1) NOT NULL, activated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deactivated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_verified TINYINT(1) NOT NULL, verified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', wallets JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', UNIQUE INDEX UNIQ_B0F6A6D5A76ED395 (user_id), INDEX IDX_B0F6A6D538248176 (currency_id), INDEX IDX_B0F6A6D582F1BAF4 (language_id), INDEX IDX_B0F6A6D5E00EB9A0 (activated_by_id), INDEX IDX_B0F6A6D569F4B775 (verified_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher_language (teacher_id INT NOT NULL, language_id INT NOT NULL, INDEX IDX_D5CDC23E41807E1D (teacher_id), INDEX IDX_D5CDC23E82F1BAF4 (language_id), PRIMARY KEY(teacher_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher_category (teacher_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_75AAA4A41807E1D (teacher_id), INDEX IDX_75AAA4A12469DE2 (category_id), PRIMARY KEY(teacher_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher_certification (id INT AUTO_INCREMENT NOT NULL, teacher_id INT DEFAULT NULL, file_id INT DEFAULT NULL, verified_by_id INT DEFAULT NULL, year_start DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', year_end DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_verified TINYINT(1) NOT NULL, verified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_A47DE30141807E1D (teacher_id), UNIQUE INDEX UNIQ_A47DE30193CB796C (file_id), INDEX IDX_A47DE30169F4B775 (verified_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher_certification_language (teacher_certification_id INT NOT NULL, language_id INT NOT NULL, INDEX IDX_EF0DE0073C64020D (teacher_certification_id), INDEX IDX_EF0DE00782F1BAF4 (language_id), PRIMARY KEY(teacher_certification_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teacher_formation (id INT AUTO_INCREMENT NOT NULL, teacher_id INT DEFAULT NULL, file_id INT DEFAULT NULL, university VARCHAR(255) NOT NULL, certificate VARCHAR(255) NOT NULL, speciality VARCHAR(255) DEFAULT NULL, year_start INT NOT NULL, year_end INT NOT NULL, INDEX IDX_3A2B6DA441807E1D (teacher_id), UNIQUE INDEX UNIQ_3A2B6DA493CB796C (file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teaching_language (id INT AUTO_INCREMENT NOT NULL, language_id INT NOT NULL, teacher_id INT NOT NULL, INDEX IDX_5AB2A18F82F1BAF4 (language_id), INDEX IDX_5AB2A18F41807E1D (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE teaching_language_language (teaching_language_id INT NOT NULL, language_id INT NOT NULL, INDEX IDX_3FEF69411E5BC6DF (teaching_language_id), INDEX IDX_3FEF694182F1BAF4 (language_id), PRIMARY KEY(teaching_language_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transaction (id INT AUTO_INCREMENT NOT NULL, currency_id INT DEFAULT NULL, user_id INT NOT NULL, responded_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', phone VARCHAR(15) DEFAULT NULL, status VARCHAR(255) NOT NULL, operator VARCHAR(255) NOT NULL, amount DOUBLE PRECISION NOT NULL, reference VARCHAR(255) NOT NULL, provider_reference VARCHAR(255) DEFAULT NULL, message VARCHAR(255) DEFAULT NULL, fee DOUBLE PRECISION DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_723705D138248176 (currency_id), INDEX IDX_723705D1A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transaction_fee (transaction_id INT NOT NULL, fee_id INT NOT NULL, INDEX IDX_6D0DD17C2FC0CB0F (transaction_id), INDEX IDX_6D0DD17CAB45AECA (fee_id), PRIMARY KEY(transaction_id, fee_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, country VARCHAR(3) DEFAULT \'CD\', last_login_ip VARCHAR(255) DEFAULT NULL, last_login_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', banned_at VARCHAR(255) DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, is_verified TINYINT(1) NOT NULL, name VARCHAR(255) DEFAULT NULL, firstname VARCHAR(255) NOT NULL, postname VARCHAR(255) DEFAULT NULL, birthday_at DATETIME DEFAULT NULL, phone VARCHAR(15) DEFAULT NULL, is_active TINYINT(1) NOT NULL, city VARCHAR(255) DEFAULT NULL, latitude VARCHAR(255) DEFAULT NULL, longitude VARCHAR(255) DEFAULT NULL, timezone VARCHAR(255) DEFAULT NULL, postal VARCHAR(255) DEFAULT NULL, ip VARCHAR(255) DEFAULT NULL, subdivisions VARCHAR(255) DEFAULT NULL, isp VARCHAR(255) DEFAULT NULL, last_login DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_phone_verified TINYINT(1) NOT NULL, language VARCHAR(5) DEFAULT \'fr\' NOT NULL, currency VARCHAR(3) DEFAULT \'USD\' NOT NULL, profile VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), UNIQUE INDEX UNIQ_8D93D649444F97DD (phone), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_language (user_id INT NOT NULL, language_id INT NOT NULL, INDEX IDX_345695B5A76ED395 (user_id), INDEX IDX_345695B582F1BAF4 (language_id), PRIMARY KEY(user_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_course (id INT AUTO_INCREMENT NOT NULL, course_id INT NOT NULL, user_id INT NOT NULL, command_id INT DEFAULT NULL, currency_id INT DEFAULT NULL, added_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', records INT DEFAULT 0 NOT NULL, start_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', end_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_buyed TINYINT(1) NOT NULL, buyed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', amount DOUBLE PRECISION NOT NULL, status VARCHAR(255) DEFAULT NULL, INDEX IDX_73CC7484591CC992 (course_id), INDEX IDX_73CC7484A76ED395 (user_id), INDEX IDX_73CC748433E1689A (command_id), INDEX IDX_73CC748438248176 (currency_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_teacher (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, teacher_id INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', hours DOUBLE PRECISION NOT NULL, buyed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_E8FBB8DFA76ED395 (user_id), INDEX IDX_E8FBB8DF41807E1D (teacher_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BB591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE attachment ADD CONSTRAINT FK_795FD9BBA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE certification_language ADD CONSTRAINT FK_1B340722CB47068A FOREIGN KEY (certification_id) REFERENCES certification (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE certification_language ADD CONSTRAINT FK_1B34072282F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB982F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB941807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB938248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB9C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE course_category ADD CONSTRAINT FK_AFF87497591CC992 FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE course_category ADD CONSTRAINT FK_AFF8749712469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE disponibility ADD CONSTRAINT FK_38BB926041807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE inbox_message ADD CONSTRAINT FK_83893680F675F31B FOREIGN KEY (author_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE inbox_message ADD CONSTRAINT FK_83893680464E68B FOREIGN KEY (attachment_id) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE inbox_message ADD CONSTRAINT FK_83893680F6619178 FOREIGN KEY (tag_message_id) REFERENCES inbox_message (id)');
        $this->addSql('ALTER TABLE inbox_message ADD CONSTRAINT FK_83893680E2904019 FOREIGN KEY (thread_id) REFERENCES inbox_thread (id)');
        $this->addSql('ALTER TABLE inbox_message ADD CONSTRAINT FK_83893680C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE inbox_thread ADD CONSTRAINT FK_B08E49AB41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE inbox_thread ADD CONSTRAINT FK_B08E49AB591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE inbox_thread ADD CONSTRAINT FK_B08E49ABC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE inbox_thread_user ADD CONSTRAINT FK_3E33875098D72D6A FOREIGN KEY (inbox_thread_id) REFERENCES inbox_thread (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inbox_thread_user ADD CONSTRAINT FK_3E338750A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE login_attempt ADD CONSTRAINT FK_8C11C1BA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F529939838248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F5299398A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F52993982FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transaction (id)');
        $this->addSql('ALTER TABLE order_product ADD CONSTRAINT FK_2530ADE641807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE order_product ADD CONSTRAINT FK_2530ADE6F44CABFF FOREIGN KEY (package_id) REFERENCES package (id)');
        $this->addSql('ALTER TABLE order_product ADD CONSTRAINT FK_2530ADE633E1689A FOREIGN KEY (command_id) REFERENCES `order` (id)');
        $this->addSql('ALTER TABLE otp ADD CONSTRAINT FK_A79C98C1A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE686795E00EB9A0 FOREIGN KEY (activated_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D38248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D8B35AB5C FOREIGN KEY (executed_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE planning ADD CONSTRAINT FK_D499BFF641807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE planning ADD CONSTRAINT FK_D499BFF6591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE planning_user ADD CONSTRAINT FK_4545DE073D865311 FOREIGN KEY (planning_id) REFERENCES planning (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE planning_user ADD CONSTRAINT FK_4545DE07A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rate ADD CONSTRAINT FK_DFEC3F3938248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D889262241807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D8892622591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D8892622A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0F591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE social ADD CONSTRAINT FK_7161E18741807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE spoken_language ADD CONSTRAINT FK_A861E9D841807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE teacher ADD CONSTRAINT FK_B0F6A6D5A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE teacher ADD CONSTRAINT FK_B0F6A6D538248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE teacher ADD CONSTRAINT FK_B0F6A6D582F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE teacher ADD CONSTRAINT FK_B0F6A6D5E00EB9A0 FOREIGN KEY (activated_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE teacher ADD CONSTRAINT FK_B0F6A6D569F4B775 FOREIGN KEY (verified_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE teacher_language ADD CONSTRAINT FK_D5CDC23E41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teacher_language ADD CONSTRAINT FK_D5CDC23E82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teacher_category ADD CONSTRAINT FK_75AAA4A41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teacher_category ADD CONSTRAINT FK_75AAA4A12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teacher_certification ADD CONSTRAINT FK_A47DE30141807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE teacher_certification ADD CONSTRAINT FK_A47DE30193CB796C FOREIGN KEY (file_id) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE teacher_certification ADD CONSTRAINT FK_A47DE30169F4B775 FOREIGN KEY (verified_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE teacher_certification_language ADD CONSTRAINT FK_EF0DE0073C64020D FOREIGN KEY (teacher_certification_id) REFERENCES teacher_certification (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teacher_certification_language ADD CONSTRAINT FK_EF0DE00782F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teacher_formation ADD CONSTRAINT FK_3A2B6DA441807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE teacher_formation ADD CONSTRAINT FK_3A2B6DA493CB796C FOREIGN KEY (file_id) REFERENCES attachment (id)');
        $this->addSql('ALTER TABLE teaching_language ADD CONSTRAINT FK_5AB2A18F82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE teaching_language ADD CONSTRAINT FK_5AB2A18F41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE teaching_language_language ADD CONSTRAINT FK_3FEF69411E5BC6DF FOREIGN KEY (teaching_language_id) REFERENCES teaching_language (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE teaching_language_language ADD CONSTRAINT FK_3FEF694182F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D138248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE transaction_fee ADD CONSTRAINT FK_6D0DD17C2FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transaction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction_fee ADD CONSTRAINT FK_6D0DD17CAB45AECA FOREIGN KEY (fee_id) REFERENCES fee (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_language ADD CONSTRAINT FK_345695B5A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_language ADD CONSTRAINT FK_345695B582F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_course ADD CONSTRAINT FK_73CC7484591CC992 FOREIGN KEY (course_id) REFERENCES course (id)');
        $this->addSql('ALTER TABLE user_course ADD CONSTRAINT FK_73CC7484A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE user_course ADD CONSTRAINT FK_73CC748433E1689A FOREIGN KEY (command_id) REFERENCES `order` (id)');
        $this->addSql('ALTER TABLE user_course ADD CONSTRAINT FK_73CC748438248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE user_teacher ADD CONSTRAINT FK_E8FBB8DFA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE user_teacher ADD CONSTRAINT FK_E8FBB8DF41807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attachment DROP FOREIGN KEY FK_795FD9BB591CC992');
        $this->addSql('ALTER TABLE attachment DROP FOREIGN KEY FK_795FD9BBA76ED395');
        $this->addSql('ALTER TABLE certification_language DROP FOREIGN KEY FK_1B340722CB47068A');
        $this->addSql('ALTER TABLE certification_language DROP FOREIGN KEY FK_1B34072282F1BAF4');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB982F1BAF4');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB941807E1D');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB938248176');
        $this->addSql('ALTER TABLE course DROP FOREIGN KEY FK_169E6FB9C76F1F52');
        $this->addSql('ALTER TABLE course_category DROP FOREIGN KEY FK_AFF87497591CC992');
        $this->addSql('ALTER TABLE course_category DROP FOREIGN KEY FK_AFF8749712469DE2');
        $this->addSql('ALTER TABLE disponibility DROP FOREIGN KEY FK_38BB926041807E1D');
        $this->addSql('ALTER TABLE inbox_message DROP FOREIGN KEY FK_83893680F675F31B');
        $this->addSql('ALTER TABLE inbox_message DROP FOREIGN KEY FK_83893680464E68B');
        $this->addSql('ALTER TABLE inbox_message DROP FOREIGN KEY FK_83893680F6619178');
        $this->addSql('ALTER TABLE inbox_message DROP FOREIGN KEY FK_83893680E2904019');
        $this->addSql('ALTER TABLE inbox_message DROP FOREIGN KEY FK_83893680C76F1F52');
        $this->addSql('ALTER TABLE inbox_thread DROP FOREIGN KEY FK_B08E49AB41807E1D');
        $this->addSql('ALTER TABLE inbox_thread DROP FOREIGN KEY FK_B08E49AB591CC992');
        $this->addSql('ALTER TABLE inbox_thread DROP FOREIGN KEY FK_B08E49ABC76F1F52');
        $this->addSql('ALTER TABLE inbox_thread_user DROP FOREIGN KEY FK_3E33875098D72D6A');
        $this->addSql('ALTER TABLE inbox_thread_user DROP FOREIGN KEY FK_3E338750A76ED395');
        $this->addSql('ALTER TABLE login_attempt DROP FOREIGN KEY FK_8C11C1BA76ED395');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F529939838248176');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F5299398A76ED395');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F52993982FC0CB0F');
        $this->addSql('ALTER TABLE order_product DROP FOREIGN KEY FK_2530ADE641807E1D');
        $this->addSql('ALTER TABLE order_product DROP FOREIGN KEY FK_2530ADE6F44CABFF');
        $this->addSql('ALTER TABLE order_product DROP FOREIGN KEY FK_2530ADE633E1689A');
        $this->addSql('ALTER TABLE otp DROP FOREIGN KEY FK_A79C98C1A76ED395');
        $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE686795E00EB9A0');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D38248176');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840DA76ED395');
        $this->addSql('ALTER TABLE payment DROP FOREIGN KEY FK_6D28840D8B35AB5C');
        $this->addSql('ALTER TABLE planning DROP FOREIGN KEY FK_D499BFF641807E1D');
        $this->addSql('ALTER TABLE planning DROP FOREIGN KEY FK_D499BFF6591CC992');
        $this->addSql('ALTER TABLE planning_user DROP FOREIGN KEY FK_4545DE073D865311');
        $this->addSql('ALTER TABLE planning_user DROP FOREIGN KEY FK_4545DE07A76ED395');
        $this->addSql('ALTER TABLE rate DROP FOREIGN KEY FK_DFEC3F3938248176');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY FK_D889262241807E1D');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY FK_D8892622591CC992');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY FK_D8892622A76ED395');
        $this->addSql('ALTER TABLE reviews DROP FOREIGN KEY FK_6970EB0F591CC992');
        $this->addSql('ALTER TABLE social DROP FOREIGN KEY FK_7161E18741807E1D');
        $this->addSql('ALTER TABLE spoken_language DROP FOREIGN KEY FK_A861E9D841807E1D');
        $this->addSql('ALTER TABLE teacher DROP FOREIGN KEY FK_B0F6A6D5A76ED395');
        $this->addSql('ALTER TABLE teacher DROP FOREIGN KEY FK_B0F6A6D538248176');
        $this->addSql('ALTER TABLE teacher DROP FOREIGN KEY FK_B0F6A6D582F1BAF4');
        $this->addSql('ALTER TABLE teacher DROP FOREIGN KEY FK_B0F6A6D5E00EB9A0');
        $this->addSql('ALTER TABLE teacher DROP FOREIGN KEY FK_B0F6A6D569F4B775');
        $this->addSql('ALTER TABLE teacher_language DROP FOREIGN KEY FK_D5CDC23E41807E1D');
        $this->addSql('ALTER TABLE teacher_language DROP FOREIGN KEY FK_D5CDC23E82F1BAF4');
        $this->addSql('ALTER TABLE teacher_category DROP FOREIGN KEY FK_75AAA4A41807E1D');
        $this->addSql('ALTER TABLE teacher_category DROP FOREIGN KEY FK_75AAA4A12469DE2');
        $this->addSql('ALTER TABLE teacher_certification DROP FOREIGN KEY FK_A47DE30141807E1D');
        $this->addSql('ALTER TABLE teacher_certification DROP FOREIGN KEY FK_A47DE30193CB796C');
        $this->addSql('ALTER TABLE teacher_certification DROP FOREIGN KEY FK_A47DE30169F4B775');
        $this->addSql('ALTER TABLE teacher_certification_language DROP FOREIGN KEY FK_EF0DE0073C64020D');
        $this->addSql('ALTER TABLE teacher_certification_language DROP FOREIGN KEY FK_EF0DE00782F1BAF4');
        $this->addSql('ALTER TABLE teacher_formation DROP FOREIGN KEY FK_3A2B6DA441807E1D');
        $this->addSql('ALTER TABLE teacher_formation DROP FOREIGN KEY FK_3A2B6DA493CB796C');
        $this->addSql('ALTER TABLE teaching_language DROP FOREIGN KEY FK_5AB2A18F82F1BAF4');
        $this->addSql('ALTER TABLE teaching_language DROP FOREIGN KEY FK_5AB2A18F41807E1D');
        $this->addSql('ALTER TABLE teaching_language_language DROP FOREIGN KEY FK_3FEF69411E5BC6DF');
        $this->addSql('ALTER TABLE teaching_language_language DROP FOREIGN KEY FK_3FEF694182F1BAF4');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D138248176');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1A76ED395');
        $this->addSql('ALTER TABLE transaction_fee DROP FOREIGN KEY FK_6D0DD17C2FC0CB0F');
        $this->addSql('ALTER TABLE transaction_fee DROP FOREIGN KEY FK_6D0DD17CAB45AECA');
        $this->addSql('ALTER TABLE user_language DROP FOREIGN KEY FK_345695B5A76ED395');
        $this->addSql('ALTER TABLE user_language DROP FOREIGN KEY FK_345695B582F1BAF4');
        $this->addSql('ALTER TABLE user_course DROP FOREIGN KEY FK_73CC7484591CC992');
        $this->addSql('ALTER TABLE user_course DROP FOREIGN KEY FK_73CC7484A76ED395');
        $this->addSql('ALTER TABLE user_course DROP FOREIGN KEY FK_73CC748433E1689A');
        $this->addSql('ALTER TABLE user_course DROP FOREIGN KEY FK_73CC748438248176');
        $this->addSql('ALTER TABLE user_teacher DROP FOREIGN KEY FK_E8FBB8DFA76ED395');
        $this->addSql('ALTER TABLE user_teacher DROP FOREIGN KEY FK_E8FBB8DF41807E1D');
        $this->addSql('DROP TABLE attachment');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE certification');
        $this->addSql('DROP TABLE certification_language');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE course');
        $this->addSql('DROP TABLE course_category');
        $this->addSql('DROP TABLE currency');
        $this->addSql('DROP TABLE disponibility');
        $this->addSql('DROP TABLE faq');
        $this->addSql('DROP TABLE fee');
        $this->addSql('DROP TABLE inbox_message');
        $this->addSql('DROP TABLE inbox_thread');
        $this->addSql('DROP TABLE inbox_thread_user');
        $this->addSql('DROP TABLE language');
        $this->addSql('DROP TABLE login_attempt');
        $this->addSql('DROP TABLE newsletter');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE `order`');
        $this->addSql('DROP TABLE order_product');
        $this->addSql('DROP TABLE otp');
        $this->addSql('DROP TABLE package');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE planning');
        $this->addSql('DROP TABLE planning_user');
        $this->addSql('DROP TABLE pricing');
        $this->addSql('DROP TABLE rate');
        $this->addSql('DROP TABLE rating');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE reviews');
        $this->addSql('DROP TABLE social');
        $this->addSql('DROP TABLE spoken_language');
        $this->addSql('DROP TABLE subscriber');
        $this->addSql('DROP TABLE teacher');
        $this->addSql('DROP TABLE teacher_language');
        $this->addSql('DROP TABLE teacher_category');
        $this->addSql('DROP TABLE teacher_certification');
        $this->addSql('DROP TABLE teacher_certification_language');
        $this->addSql('DROP TABLE teacher_formation');
        $this->addSql('DROP TABLE teaching_language');
        $this->addSql('DROP TABLE teaching_language_language');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE transaction_fee');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE user_language');
        $this->addSql('DROP TABLE user_course');
        $this->addSql('DROP TABLE user_teacher');
    }
}
