# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'


  kimia_api.event.jwt_created_listener:
    class: App\EventListener\JWTCreatedListener
    arguments: [ '@request_stack' ]
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

  kimia_api.event.jwt_authentication_success_listener:
    class: App\EventListener\JWTAuthenticationSuccessListener
    arguments: [ '@request_stack' ]
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }

  App\State\Teacher\TeacherPricingProcessor:
    bind:
      $processor: '@api_platform.doctrine.orm.state.persist_processor'

  App\State\User\UserPasswordHasher:
    bind:
      $processor: '@api_platform.doctrine.orm.state.persist_processor'

  App\Service\Gateway\FlexPaieGateway:
    tags: [ 'app.payment_gateway' ]
    bind:
      $secret: '%env(resolve:FLEXPAY)%'

  App\Service\OperatorProcess:
    arguments:
      $gateways: !tagged app.payment_gateway

  mjml_api:
    class: Mjml\Client
    arguments:
      - '%env(MJML_ID)%'
      - '%env(MJML_SECRET)%'

  App\Mjml\ApiRenderer:
    arguments:
      - '@mjml_api'