# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    payment_provider: '%env(PAYMENT_PROVIDER)%'
    flexpay_endpoint: '%env(FLEXPAY_ENDPOINT)%'
    flexpay_merchant_name: '%env(FLEXPAY_MERCHANT_NAME)%'
    flexpay_token: '%env(FLEXPAY_TOKEN)%'
    merchant_name: '%env(MERCHANT_NAME)%'
    CLOUDINARY_URL: '%env(CLOUDINARY_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Service\Config:
        arguments:
            $flexpayToken: '%flexpay_token%'
            $flexpayEndpoint: '%flexpay_endpoint%'
            $merchantName: '%merchant_name%'

    App\Service\OperatorProcess:
        arguments:
            $provider: '%payment_provider%'

    App\Service\Payment\FlexPayProvider:
        arguments:
            $flexpayToken: '%flexpay_token%'
            $flexpayEndpoint: '%flexpay_endpoint%'
            $merchantName: '%flexpay_merchant_name%'

    App\Service\Payment\PaymentManager:
        arguments:
            $provider: '%payment_provider%'
            $flexPayProvider: '@App\Service\Payment\FlexPayProvider'

    App\EventListener\ConflictExceptionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', priority: 100 }

    App\EventListener\AccessDeniedListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception', priority: 50 }

    App\Service\CloudinaryService:
        arguments:
            $cloudinaryUrl: '%env(CLOUDINARY_URL)%'

    App\EventListener\VideoUploadListener:
        tags:
            - { name: 'vich_uploader.event_listener', event: 'vich_uploader.post_upload', method: 'onVichUploaderPostUpload' }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
